---
title: "Rworksheet_cadiz#3b"
author: "John Dave R. Cadiz"
date: "2024-10-02"
output: pdf_document
---

## 1. Create a data frame using the table below..

```{r}
## a. Write the codes.
data <- data.frame(
                  Respondents = 1:20,
                  Sex = c(2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1,
                          1, 2),
                  FathersOccupation = c(1, 3, 1, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 
                                         3, 1, 2, 3, 1, 2, 1),
                  PersonsAtHome = c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 
                                      8, 8, 3, 11, 7, 6),
                  SiblingsAtSchool = c(6, 4, 4, 1, 2, 3, 5, 3, 2, 4, 2, 5, 5, 
                                         5, 2, 1, 2, 5, 3, 2),
                  TypesOfHouses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 
                                      3, 3, 3, 3, 3, 2))
```
```{r}
## b. Describe the data. Get the structure or the summary of the data
#The data consist of 20 respondents together with the variable names such as sex, 
#fathers occupation, Persons at home, Siblings at school, and the type of houses
str(data)
summary(data)

```

```{r}
## c. Is the mean number of siblings attending is 5?
meansib <- mean(data$SiblingsAtSchool)
meansib ==5
```

```{r}
## d. Extract the 1st two rows and then all the columns using the subsetting functions.
## Write the codes and its output.
firstTwoRows <- data[1:2, ]
print(firstTwoRows)
```

```{r}
## e. Extract 3rd and 5th row and 4th column. Write the code and its result.
exrow3n5col4 <- data[c(3,5), c(2,4)]
print(exrow3n5col4)
```

```{r}
## f. Select the variable types of the houses then store the vector that result as
#type_houses. Write the codes

type_houses <- data$TypesOfHouses
print(type_houses)
```

```{r}
## g. Select only all Males respondent that their father occupation was farmer. 
## Write the codes and its output.

maleFarmer <- subset(data, Sex == 1 & FathersOccupation == 1)
print(maleFarmer)
```

```{r}
## h. Select only all females respondent that have greater than or equal to 5 number
## of siblings attending school. Write the codes and its output.
femaleSibs <- subset(data, Sex == 2 & SiblingsAtSchool >= 5)
print(femaleSibs)
```

## 2. Write a R programe to create an empty data frame. Using the following codes:
```{r}
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
```

```{r}
## a. Describe the results.
## It shows that the data frame is empty and represents each different data types
## in five columns, since there is no data the observations remain 0.
```

## 3. Create a .csv file of this. save it as HouseholdData.csv

```{r}
## a. Import the csv file into the R environment. Write the codes
data <- read.csv("HouseholdData.csv", header = TRUE, stringsAsFactors = FALSE)
print(data)
```
```{r}
## b. Convert the Sex into factor using factor() function and change it into
## integer.[Legend: Male = 1 and Female = 2]. Write the R codes and its output.
data$Sex <- factor(data$Sex,
                   levels = c("Male", "Female"),
                   labels = c(1,2))
data$Sex <- as.integer(as.character(data$Sex))
print(data)
```

```{r}
## c. Convert the Type of Houses into factor and change it into integer. [Legend:
## Wood = 1; Congrete= 2; Semi-Congrete = 3]. Write the R codes and its output.
data$TypesOfHouses <- factor(data$Types.of.Houses,
                             levels = c("Wood", "Congrete", "Semi-Congrete"),
                             labels = c(1, 2, 3))
data$Types.of.Houses <- as.integer(data$Types.of.Houses)
print(data)
```

```{r}
## d. On father's occupation, factor it as Farmer = 1, Driver = 2, and other = 3
## What is the R codes and its output.
data$Fathers.Occupation <- factor(data$Fathers.Occupation,
                                  levels = c(1, 2, 3),
                                  labels = c("Farmer", "Driver", "Others"))
data$Fathers.Occupation <- as.character(data$Fathers.Occupation)
print(data)
```

```{r}
## e. Select only all females respondent that has a father whose occupation is driver.
## Write the R codes and its output.

femRes <- subset(data, Sex == 2 & Fathers.Occupation == "Driver")
print(femRes)
```

```{r}
## f. Select the respondents that have greater than or equal to 5 numbers of siblings
## attending school. Write the codes and its output.

sib5 <- subset(data, Siblings.at.School >= 5)
print(sib5)
```

